/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface PrStockFinder {}
  interface PrStockPrice {
    'stockSymbol': string;
  }
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLPrStockFinderElement extends Components.PrStockFinder, HTMLStencilElement {}
  var HTMLPrStockFinderElement: {
    prototype: HTMLPrStockFinderElement;
    new (): HTMLPrStockFinderElement;
  };

  interface HTMLPrStockPriceElement extends Components.PrStockPrice, HTMLStencilElement {}
  var HTMLPrStockPriceElement: {
    prototype: HTMLPrStockPriceElement;
    new (): HTMLPrStockPriceElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'pr-stock-finder': HTMLPrStockFinderElement;
    'pr-stock-price': HTMLPrStockPriceElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface PrStockFinder {
    'onPrSymbolSelected'?: (event: CustomEvent<string>) => void;
  }
  interface PrStockPrice {
    'stockSymbol'?: string;
  }

  interface IntrinsicElements {
    'my-component': MyComponent;
    'pr-stock-finder': PrStockFinder;
    'pr-stock-price': PrStockPrice;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'pr-stock-finder': LocalJSX.PrStockFinder & JSXBase.HTMLAttributes<HTMLPrStockFinderElement>;
      'pr-stock-price': LocalJSX.PrStockPrice & JSXBase.HTMLAttributes<HTMLPrStockPriceElement>;
    }
  }
}


